# Generated by Django 3.2.5 on 2022-01-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
